// yuejiao-web/前端代码/src/views/report/NameTable.vue
<script setup lang="ts">
export interface NameTableColumn {
  key: string
  label: string
}

defineProps<{
  columns: NameTableColumn[]
  rows: Record<string, string | number>[]
}>()
</script>

<template>
  <div class="roster">
    <table>
      <thead>
        <tr>
          <th v-for="column in columns" :key="column.key">{{ column.label }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(row, index) in rows" :key="index">
          <td v-for="column in columns" :key="column.key">{{ row[column.key] }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<style scoped>
.roster {
  max-height: 320px;
  overflow: auto;
  margin: 0 0 12px;
  border: 1px solid #ebeef5;
  border-radius: 4px;
}

table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}

th,
td {
  padding: 8px 10px;
  text-align: left;
  vertical-align: top;
  line-height: 1.5;
}

th {
  position: sticky;
  top: 0;
  z-index: 1;
  background: #fafafa;
  color: #606266;
  font-weight: 600;
  border-bottom: 1px solid #e4e7ed;
}

td {
  border-bottom: 1px dashed #ebeef5;
  color: #303133;
  white-space: pre-line;
}

tbody tr:last-child td {
  border-bottom: none;
}
</style>

// yuejiao-web/react-frontend/src/pages/report/NameTable.tsx
// 等价移植自 Vue 版 前端代码/src/views/report/NameTable.vue:
// 原生 table、sticky 表头、max-height 320 内滚、td white-space:pre-line。
export interface NameTableColumn {
  key: string
  label: string
}

export function NameTable({
  columns,
  rows,
}: {
  columns: NameTableColumn[]
  rows: Record<string, string | number>[]
}) {
  return (
    <div className="roster">
      <table>
        <thead>
          <tr>
            {columns.map((column) => (
              <th key={column.key}>{column.label}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, index) => (
            <tr key={index}>
              {columns.map((column) => (
                <td key={column.key}>{row[column.key]}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
