// yuejiao-web/前端代码/src/components/BarList.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  items: { label: string; value: number; color?: string }[]
}>()

const palette = ['#c41e1e', '#9d1818', '#1d1e1f', '#d95454', '#606266']
const max = computed(() => Math.max(1, ...props.items.map((item) => Number(item.value) || 0)))
</script>

<template>
  <div class="bar-list">
    <div v-for="(item, index) in items" :key="item.label" class="bar-row">
      <span class="funnel-label">{{ item.label }}</span>
      <div class="funnel-track">
        <div
          class="funnel-bar"
          :style="{
            width: `${((Number(item.value) || 0) / max) * 100}%`,
            background: item.color || palette[index % palette.length],
          }"
        />
      </div>
      <strong>{{ item.value }}</strong>
    </div>
  </div>
</template>

// yuejiao-web/react-frontend/src/components/BarList.tsx
// 等价迁移自 components/BarList.vue
const PALETTE = ['#c41e1e', '#9d1818', '#1d1e1f', '#d95454', '#606266']

export interface BarListItem {
  label: string
  value: number
  color?: string
}

export function BarList({ items }: { items: BarListItem[] }) {
  const max = Math.max(1, ...items.map((item) => Number(item.value) || 0))
  return (
    <div className="bar-list">
      {items.map((item, index) => (
        <div key={item.label} className="bar-row">
          <span className="funnel-label">{item.label}</span>
          <div className="funnel-track">
            <div
              className="funnel-bar"
              style={{
                width: `${((Number(item.value) || 0) / max) * 100}%`,
                background: item.color || PALETTE[index % PALETTE.length],
              }}
            />
          </div>
          <strong>{item.value}</strong>
        </div>
      ))}
    </div>
  )
}
